/**
 * OpenPrice Rich Mock Seed Engine
 * Provides 7 retail stores, 20 multi-category products, ~1,500+ longitudinal price points (1-year),
 * category taxonomies, and 3 ground-truth OCR sample documents with normalized bounding boxes.
 */

import type {
  Product,
  Store,
  PricePoint,
  CategoryMetadata,
  OcrParseResult,
  ProductCategory,
} from '../types/index.ts';

export const CATEGORY_METADATA: Record<ProductCategory, CategoryMetadata> = {
  groceries: {
    id: 'groceries',
    displayName: 'Groceries & Produce',
    description: 'Fresh produce, dairy, bakery, meat, and staple food items',
    iconName: 'ShoppingBasket',
    inflationBasketWeight: 0.35,
    colorAccent: '#10B981',
  },
  beverages: {
    id: 'beverages',
    displayName: 'Beverages & Drinks',
    description: 'Coffee, teas, sparkling water, juices, and specialty drinks',
    iconName: 'Coffee',
    inflationBasketWeight: 0.15,
    colorAccent: '#06B6D4',
  },
  household: {
    id: 'household',
    displayName: 'Household & Cleaning',
    description: 'Detergents, paper goods, soaps, and cleaning supplies',
    iconName: 'Home',
    inflationBasketWeight: 0.15,
    colorAccent: '#8B5CF6',
  },
  pharmacy: {
    id: 'pharmacy',
    displayName: 'Pharmacy & Wellness',
    description: 'Over-the-counter medicine, vitamins, and personal care',
    iconName: 'HeartPulse',
    inflationBasketWeight: 0.10,
    colorAccent: '#F43F5E',
  },
  electronics: {
    id: 'electronics',
    displayName: 'Consumer Electronics',
    description: 'Chargers, cables, audio accessories, and smart devices',
    iconName: 'Smartphone',
    inflationBasketWeight: 0.10,
    colorAccent: '#6366F1',
  },
  apparel: {
    id: 'apparel',
    displayName: 'Apparel & Basics',
    description: 'Everyday clothing, athletic wear, and socks',
    iconName: 'Shirt',
    inflationBasketWeight: 0.08,
    colorAccent: '#EC4899',
  },
  services: {
    id: 'services',
    displayName: 'Local Services',
    description: 'Dry cleaning, automotive maintenance, and household repair',
    iconName: 'Wrench',
    inflationBasketWeight: 0.07,
    colorAccent: '#F59E0B',
  },
};

export const SEED_STORES: Store[] = [
  {
    id: 'store-target',
    name: 'Target',
    chain: 'Target Corp',
    branchName: 'Downtown Metro',
    type: 'physical',
    city: 'Seattle',
    state: 'WA',
    address: '1401 2nd Ave, Seattle, WA 98101',
    color: '#0EA5E9',
    isVerified: true,
  },
  {
    id: 'store-walmart',
    name: 'Walmart Supercenter',
    chain: 'Walmart Inc',
    branchName: 'West Valley',
    type: 'physical',
    city: 'Renton',
    state: 'WA',
    address: '743 Rainier Ave S, Renton, WA 98057',
    color: '#10B981',
    isVerified: true,
  },
  {
    id: 'store-trader-joes',
    name: "Trader Joe's",
    chain: "Trader Joe's",
    branchName: 'Capitol Hill',
    type: 'physical',
    city: 'Seattle',
    state: 'WA',
    address: '1700 E Madison St, Seattle, WA 98122',
    color: '#8B5CF6',
    isVerified: true,
  },
  {
    id: 'store-whole-foods',
    name: 'Whole Foods Market',
    chain: 'Amazon Whole Foods',
    branchName: 'South Lake Union',
    type: 'hybrid',
    city: 'Seattle',
    state: 'WA',
    address: '2210 Westlake Ave, Seattle, WA 98121',
    color: '#F43F5E',
    isVerified: true,
  },
  {
    id: 'store-kroger',
    name: 'Ralphs / QFC',
    chain: 'Kroger Co',
    branchName: 'University Village',
    type: 'physical',
    city: 'Seattle',
    state: 'WA',
    address: '2746 NE 45th St, Seattle, WA 98105',
    color: '#6366F1',
    isVerified: true,
  },
  {
    id: 'store-costco',
    name: 'Costco Wholesale',
    chain: 'Costco Wholesale Corp',
    branchName: '4th Ave S',
    type: 'physical',
    city: 'Seattle',
    state: 'WA',
    address: '4401 4th Ave S, Seattle, WA 98134',
    color: '#F59E0B',
    isVerified: true,
  },
  {
    id: 'store-amazon-fresh',
    name: 'Amazon Fresh',
    chain: 'Amazon.com Inc',
    branchName: 'Central Online & Physical',
    type: 'online',
    city: 'Seattle',
    state: 'WA',
    address: 'Online / Jackson St, Seattle, WA 98144',
    color: '#EC4899',
    isVerified: true,
  },
];

const HISTORICAL_MONTHS = [
  '2025-08-15T10:00:00.000Z',
  '2025-09-15T10:00:00.000Z',
  '2025-10-15T10:00:00.000Z',
  '2025-11-15T10:00:00.000Z',
  '2025-12-15T10:00:00.000Z',
  '2026-01-15T10:00:00.000Z',
  '2026-02-15T10:00:00.000Z',
  '2026-03-15T10:00:00.000Z',
  '2026-04-15T10:00:00.000Z',
  '2026-05-15T10:00:00.000Z',
  '2026-06-15T10:00:00.000Z',
  '2026-07-15T10:00:00.000Z',
  '2026-08-15T10:00:00.000Z',
  '2026-08-24T10:00:00.000Z',
];

const CONTRIBUTORS = [
  { id: 'contrib-1', name: 'Alex Rivera (Master Curator)' },
  { id: 'contrib-2', name: 'Elena Chen (Eagle Eye)' },
  { id: 'contrib-3', name: 'Marcus Vance (Price Hunter)' },
  { id: 'contrib-4', name: 'Sara Novak (Novice Scout)' },
];

/**
 * Deterministically generates realistic longitudinal 1-year historical price observations
 * for each product across tracked stores with seasonal shifts, discounts, and verified provenance.
 */
function generateHistoricalPricePoints(
  productId: string,
  basePrice: number,
  stores: Store[],
  trendDirection: 'drop' | 'hike' | 'stable' = 'stable',
  unit: string = 'each'
): PricePoint[] {
  const points: PricePoint[] = [];

  stores.forEach((store, storeIndex) => {
    // Store price tier multiplier: Walmart/Costco cheaper, Whole Foods premium
    const storeMultiplier = 0.90 + (storeIndex * 0.035);

    HISTORICAL_MONTHS.forEach((timestamp, monthIndex) => {
      // Natural price evolution curve
      let driftFactor = 1.0;
      const progress = monthIndex / (HISTORICAL_MONTHS.length - 1);

      if (trendDirection === 'drop') {
        driftFactor = 1.08 - (progress * 0.14); // 8% above base down to 6% below base
      } else if (trendDirection === 'hike') {
        driftFactor = 0.92 + (progress * 0.16); // 8% below base up to 8% above base
      } else {
        driftFactor = 1.0 + (Math.sin(monthIndex + storeIndex) * 0.025);
      }

      // Periodic seasonal promotional discount
      const isDiscounted = (monthIndex === 3 || monthIndex === 8 || monthIndex === 12) && storeIndex % 2 === 0;
      const regularPrice = Number((basePrice * storeMultiplier * driftFactor).toFixed(2));
      const finalPrice = isDiscounted
        ? Number((regularPrice * 0.85).toFixed(2))
        : regularPrice;

      const contributor = CONTRIBUTORS[(monthIndex + storeIndex) % CONTRIBUTORS.length];
      const sourceTypes: PricePoint['sourceType'][] = [
        'photo_shelf',
        'promo_pamphlet',
        'receipt',
        'web_crawler',
      ];
      const sourceType = sourceTypes[(monthIndex * 2 + storeIndex) % sourceTypes.length];

      points.push({
        id: `pp-${productId}-${store.id}-${monthIndex}`,
        productId,
        storeId: store.id,
        storeName: store.name,
        price: finalPrice,
        originalPrice: isDiscounted ? regularPrice : undefined,
        currency: 'USD',
        unit,
        timestamp,
        sourceType,
        confidenceScore: 90 + ((monthIndex * 3 + storeIndex * 7) % 10),
        contributorId: contributor.id,
        contributorName: contributor.name,
        isVerified: true,
        proofImageUrl: sourceType === 'photo_shelf'
          ? '/samples/shelf-tag-milk.jpg'
          : sourceType === 'receipt'
          ? '/samples/grocery-receipt-trader-joes.jpg'
          : undefined,
      });
    });
  });

  return points;
}

// 20 Multi-Category Tracked Products
export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-milk',
    name: 'Organic Whole Milk',
    brand: 'Horizon Organic',
    category: 'groceries',
    unit: '1 Gallon',
    description: 'USDA certified organic whole milk with Vitamin D3 and pasteurized freshness.',
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    currentLowestPrice: 4.89,
    currentHighestPrice: 6.29,
    averagePrice: 5.45,
    previousPrice: 5.79,
    trendStatus: 'price_drop',
    priceDeltaPercent: -5.87,
    priceDeltaAmount: -0.34,
    trackedStoresCount: 7,
    totalSubmissionsCount: 98,
    historicalPrices: generateHistoricalPricePoints('prod-milk', 5.50, SEED_STORES, 'drop', '1 Gallon'),
    isVerified: true,
    tags: ['dairy', 'organic', 'staple', 'milk'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-eggs',
    name: 'Pasture-Raised Large Brown Eggs',
    brand: 'Vital Farms',
    category: 'groceries',
    unit: '12 ct',
    description: 'Pasture-raised grade A large brown eggs from pasture-foraging hens.',
    imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400',
    currentLowestPrice: 5.49,
    currentHighestPrice: 7.99,
    averagePrice: 6.74,
    previousPrice: 6.19,
    trendStatus: 'price_hike',
    priceDeltaPercent: 8.88,
    priceDeltaAmount: 0.55,
    trackedStoresCount: 6,
    totalSubmissionsCount: 84,
    historicalPrices: generateHistoricalPricePoints('prod-eggs', 6.20, SEED_STORES.slice(0, 6), 'hike', '12 ct'),
    isVerified: true,
    tags: ['dairy', 'eggs', 'pasture-raised', 'protein'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-bread',
    name: 'Artisanal San Francisco Sourdough',
    brand: 'Boudin Bakery',
    category: 'groceries',
    unit: '24 oz loaf',
    description: 'Naturally fermented San Francisco sourdough bread loaf with crisp golden crust.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    currentLowestPrice: 3.99,
    currentHighestPrice: 5.49,
    averagePrice: 4.65,
    previousPrice: 4.65,
    trendStatus: 'stable',
    priceDeltaPercent: 0.0,
    priceDeltaAmount: 0.0,
    trackedStoresCount: 5,
    totalSubmissionsCount: 70,
    historicalPrices: generateHistoricalPricePoints('prod-bread', 4.50, SEED_STORES.slice(0, 5), 'stable', '24 oz loaf'),
    isVerified: true,
    tags: ['bakery', 'bread', 'sourdough', 'carbs'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-coffee',
    name: 'Fair Trade Dark Roast Coffee Beans',
    brand: 'Peet’s Coffee',
    category: 'beverages',
    unit: '12 oz bag',
    description: 'Major Dickason’s Blend whole bean dark roast coffee rich and aromatic.',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400',
    currentLowestPrice: 9.99,
    currentHighestPrice: 14.49,
    averagePrice: 12.19,
    previousPrice: 12.99,
    trendStatus: 'price_drop',
    priceDeltaPercent: -6.16,
    priceDeltaAmount: -0.80,
    trackedStoresCount: 7,
    totalSubmissionsCount: 98,
    historicalPrices: generateHistoricalPricePoints('prod-coffee', 12.50, SEED_STORES, 'drop', '12 oz bag'),
    isVerified: true,
    tags: ['beverages', 'coffee', 'dark-roast', 'caffeine'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-apples',
    name: 'Honeycrisp Apples',
    brand: 'Stemilt Growers',
    category: 'groceries',
    unit: '3 lb bag',
    description: 'Crisp and juicy sweet Washington State Honeycrisp apples.',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400',
    currentLowestPrice: 4.49,
    currentHighestPrice: 6.99,
    averagePrice: 5.65,
    previousPrice: 5.29,
    trendStatus: 'price_hike',
    priceDeltaPercent: 6.81,
    priceDeltaAmount: 0.36,
    trackedStoresCount: 6,
    totalSubmissionsCount: 84,
    historicalPrices: generateHistoricalPricePoints('prod-apples', 5.40, SEED_STORES.slice(0, 6), 'hike', '3 lb bag'),
    isVerified: true,
    tags: ['produce', 'fruit', 'apples', 'fresh'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-chicken',
    name: 'Organic Boneless Chicken Breasts',
    brand: 'Foster Farms',
    category: 'groceries',
    unit: '1 lb',
    description: 'Air-chilled organic boneless skinless chicken breasts with zero antibiotics.',
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400',
    currentLowestPrice: 6.99,
    currentHighestPrice: 9.49,
    averagePrice: 8.15,
    previousPrice: 8.15,
    trendStatus: 'stable',
    priceDeltaPercent: 0.0,
    priceDeltaAmount: 0.0,
    trackedStoresCount: 5,
    totalSubmissionsCount: 70,
    historicalPrices: generateHistoricalPricePoints('prod-chicken', 8.00, SEED_STORES.slice(0, 5), 'stable', '1 lb'),
    isVerified: true,
    tags: ['meat', 'poultry', 'organic', 'protein'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-olive-oil',
    name: 'Extra Virgin Cold-Pressed Olive Oil',
    brand: 'California Olive Ranch',
    category: 'groceries',
    unit: '500 ml bottle',
    description: '100% California extra virgin cold-pressed olive oil for cooking and dressing.',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    currentLowestPrice: 13.99,
    currentHighestPrice: 18.99,
    averagePrice: 16.49,
    previousPrice: 17.99,
    trendStatus: 'price_drop',
    priceDeltaPercent: -8.34,
    priceDeltaAmount: -1.50,
    trackedStoresCount: 6,
    totalSubmissionsCount: 84,
    historicalPrices: generateHistoricalPricePoints('prod-olive-oil', 16.50, SEED_STORES.slice(0, 6), 'drop', '500 ml'),
    isVerified: true,
    tags: ['pantry', 'oil', 'olive-oil', 'cooking'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-rice',
    name: 'Royal Jasmine White Rice',
    brand: 'Lundberg Family Farms',
    category: 'groceries',
    unit: '5 lb bag',
    description: 'Aromatic long grain California white jasmine rice, sustainably farmed.',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    currentLowestPrice: 7.49,
    currentHighestPrice: 9.99,
    averagePrice: 8.65,
    previousPrice: 8.65,
    trendStatus: 'stable',
    priceDeltaPercent: 0.0,
    priceDeltaAmount: 0.0,
    trackedStoresCount: 5,
    totalSubmissionsCount: 70,
    historicalPrices: generateHistoricalPricePoints('prod-rice', 8.50, SEED_STORES.slice(0, 5), 'stable', '5 lb bag'),
    isVerified: true,
    tags: ['pantry', 'grain', 'rice', 'staple'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-butter',
    name: 'Pure Irish Grass-Fed Butter',
    brand: 'Kerrygold',
    category: 'groceries',
    unit: '8 oz (2 bars)',
    description: 'Imported salted butter made from grass-fed Irish cows with golden richness.',
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400',
    currentLowestPrice: 4.29,
    currentHighestPrice: 5.99,
    averagePrice: 5.15,
    previousPrice: 4.89,
    trendStatus: 'price_hike',
    priceDeltaPercent: 5.32,
    priceDeltaAmount: 0.26,
    trackedStoresCount: 6,
    totalSubmissionsCount: 84,
    historicalPrices: generateHistoricalPricePoints('prod-butter', 5.00, SEED_STORES.slice(0, 6), 'hike', '8 oz'),
    isVerified: true,
    tags: ['dairy', 'butter', 'grass-fed', 'staple'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-salmon',
    name: 'Wild Alaskan Sockeye Salmon Fillet',
    brand: 'Ocean Beauty',
    category: 'groceries',
    unit: '1 lb',
    description: 'Sustainably caught wild Alaskan sockeye salmon fillet rich in Omega-3.',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400',
    currentLowestPrice: 14.99,
    currentHighestPrice: 19.99,
    averagePrice: 17.45,
    previousPrice: 18.99,
    trendStatus: 'price_drop',
    priceDeltaPercent: -8.11,
    priceDeltaAmount: -1.54,
    trackedStoresCount: 5,
    totalSubmissionsCount: 70,
    historicalPrices: generateHistoricalPricePoints('prod-salmon', 17.50, SEED_STORES.slice(0, 5), 'drop', '1 lb'),
    isVerified: true,
    tags: ['seafood', 'fresh', 'salmon', 'protein'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-headphones',
    name: 'Wireless ANC Noise Cancelling Headphones',
    brand: 'Sony',
    category: 'electronics',
    unit: '1 unit',
    description: 'WH-1000XM5 wireless industry leading noise cancelling headphones with dual processors.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    currentLowestPrice: 329.99,
    currentHighestPrice: 399.99,
    averagePrice: 368.50,
    previousPrice: 399.99,
    trendStatus: 'price_drop',
    priceDeltaPercent: -7.87,
    priceDeltaAmount: -31.49,
    trackedStoresCount: 4,
    totalSubmissionsCount: 56,
    historicalPrices: generateHistoricalPricePoints('prod-headphones', 370.00, SEED_STORES.slice(0, 4), 'drop', '1 unit'),
    isVerified: true,
    tags: ['audio', 'tech', 'headphones', 'bluetooth'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-charger',
    name: '65W Dual USB-C GaN Fast Wall Charger',
    brand: 'Anker',
    category: 'electronics',
    unit: '1 unit',
    description: 'Compact 65W fast charger with PowerIQ 4.0 for laptops, tablets, and phones.',
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400',
    currentLowestPrice: 29.99,
    currentHighestPrice: 42.99,
    averagePrice: 36.45,
    previousPrice: 36.45,
    trendStatus: 'stable',
    priceDeltaPercent: 0.0,
    priceDeltaAmount: 0.0,
    trackedStoresCount: 4,
    totalSubmissionsCount: 56,
    historicalPrices: generateHistoricalPricePoints('prod-charger', 35.00, SEED_STORES.slice(0, 4), 'stable', '1 unit'),
    isVerified: true,
    tags: ['accessories', 'power', 'charger', 'usb-c'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-cable',
    name: 'Braided USB-C to USB-C Cable (2m)',
    brand: 'Belkin',
    category: 'electronics',
    unit: '2m cable',
    description: 'Durable nylon braided 100W Power Delivery high-speed charging and sync cable.',
    imageUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=400',
    currentLowestPrice: 12.99,
    currentHighestPrice: 19.99,
    averagePrice: 15.95,
    previousPrice: 14.49,
    trendStatus: 'price_hike',
    priceDeltaPercent: 10.08,
    priceDeltaAmount: 1.46,
    trackedStoresCount: 4,
    totalSubmissionsCount: 56,
    historicalPrices: generateHistoricalPricePoints('prod-cable', 15.00, SEED_STORES.slice(0, 4), 'hike', '2m cable'),
    isVerified: true,
    tags: ['cables', 'accessories', 'usb-c'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-smart-bulb',
    name: 'Matter Smart Color LED Bulb 2-Pack',
    brand: 'Nanoleaf',
    category: 'electronics',
    unit: '2-pack',
    description: 'Thread and Matter enabled A19 smart multicolor light bulbs with app and voice control.',
    imageUrl: 'https://images.unsplash.com/photo-1550985616-10810253b84d?w=400',
    currentLowestPrice: 24.99,
    currentHighestPrice: 34.99,
    averagePrice: 29.50,
    previousPrice: 32.99,
    trendStatus: 'price_drop',
    priceDeltaPercent: -10.58,
    priceDeltaAmount: -3.49,
    trackedStoresCount: 4,
    totalSubmissionsCount: 56,
    historicalPrices: generateHistoricalPricePoints('prod-smart-bulb', 30.00, SEED_STORES.slice(0, 4), 'drop', '2-pack'),
    isVerified: true,
    tags: ['smarthome', 'lighting', 'matter', 'led'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-detergent',
    name: 'Eco Laundry Detergent Pods (42 ct)',
    brand: 'Seventh Generation',
    category: 'household',
    unit: '42 count tub',
    description: 'Plant-based enzyme powered concentrated laundry detergent pods with zero synthetic dyes.',
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400',
    currentLowestPrice: 14.49,
    currentHighestPrice: 19.49,
    averagePrice: 16.95,
    previousPrice: 15.99,
    trendStatus: 'price_hike',
    priceDeltaPercent: 6.00,
    priceDeltaAmount: 0.96,
    trackedStoresCount: 6,
    totalSubmissionsCount: 84,
    historicalPrices: generateHistoricalPricePoints('prod-detergent', 16.00, SEED_STORES.slice(0, 6), 'hike', '42 count'),
    isVerified: true,
    tags: ['cleaning', 'eco', 'laundry', 'household'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-paper-towels',
    name: 'Ultra Absorbent Paper Towels (6 Double Rolls)',
    brand: 'Bounty',
    category: 'household',
    unit: '6 double rolls',
    description: 'The Quicker Picker Upper 2-ply select-a-size paper towels for tough kitchen messes.',
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400',
    currentLowestPrice: 11.99,
    currentHighestPrice: 16.99,
    averagePrice: 14.45,
    previousPrice: 14.45,
    trendStatus: 'stable',
    priceDeltaPercent: 0.0,
    priceDeltaAmount: 0.0,
    trackedStoresCount: 6,
    totalSubmissionsCount: 84,
    historicalPrices: generateHistoricalPricePoints('prod-paper-towels', 14.00, SEED_STORES.slice(0, 6), 'stable', '6 rolls'),
    isVerified: true,
    tags: ['paper', 'essentials', 'kitchen', 'cleaning'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-dish-soap',
    name: 'Plant-Based Dishwashing Liquid (28 oz)',
    brand: 'Method',
    category: 'household',
    unit: '28 fl oz',
    description: 'Biodegradable Clementine grease-fighting dish soap with naturally derived surfactants.',
    imageUrl: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400',
    currentLowestPrice: 3.99,
    currentHighestPrice: 5.49,
    averagePrice: 4.75,
    previousPrice: 4.99,
    trendStatus: 'price_drop',
    priceDeltaPercent: -4.81,
    priceDeltaAmount: -0.24,
    trackedStoresCount: 5,
    totalSubmissionsCount: 70,
    historicalPrices: generateHistoricalPricePoints('prod-dish-soap', 4.80, SEED_STORES.slice(0, 5), 'drop', '28 fl oz'),
    isVerified: true,
    tags: ['cleaning', 'dish', 'eco', 'kitchen'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-ibuprofen',
    name: 'Ibuprofen Pain Reliever Tablets 200mg (100 ct)',
    brand: 'Advil',
    category: 'pharmacy',
    unit: '100 coated tablets',
    description: 'Fast acting NSAID pain and fever reducer coated tablets.',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
    currentLowestPrice: 9.49,
    currentHighestPrice: 13.99,
    averagePrice: 11.75,
    previousPrice: 11.20,
    trendStatus: 'price_hike',
    priceDeltaPercent: 4.91,
    priceDeltaAmount: 0.55,
    trackedStoresCount: 5,
    totalSubmissionsCount: 70,
    historicalPrices: generateHistoricalPricePoints('prod-ibuprofen', 11.50, SEED_STORES.slice(0, 5), 'hike', '100 ct'),
    isVerified: true,
    tags: ['health', 'medication', 'pain-relief', 'pharmacy'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-sparkling-water',
    name: 'Natural Sparkling Mineral Water (12 pack)',
    brand: 'LaCroix',
    category: 'beverages',
    unit: '12 x 12 oz cans',
    description: 'Pamplemousse grapefruit 100% natural flavored sparkling water with zero sodium and zero calories.',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400',
    currentLowestPrice: 4.99,
    currentHighestPrice: 6.99,
    averagePrice: 5.85,
    previousPrice: 5.85,
    trendStatus: 'stable',
    priceDeltaPercent: 0.0,
    priceDeltaAmount: 0.0,
    trackedStoresCount: 6,
    totalSubmissionsCount: 84,
    historicalPrices: generateHistoricalPricePoints('prod-sparkling-water', 5.80, SEED_STORES.slice(0, 6), 'stable', '12 pack'),
    isVerified: true,
    tags: ['beverages', 'water', 'sparkling', 'zero-sugar'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'prod-dry-cleaning',
    name: 'Eco 2-Piece Wool Suit Dry Cleaning',
    brand: 'GreenEarth Cleaners',
    category: 'services',
    unit: '1 suit service',
    description: 'Silicone-based non-toxic eco garment dry cleaning with hand press and stain treatment.',
    imageUrl: 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=400',
    currentLowestPrice: 16.00,
    currentHighestPrice: 24.00,
    averagePrice: 19.50,
    previousPrice: 18.00,
    trendStatus: 'price_hike',
    priceDeltaPercent: 8.33,
    priceDeltaAmount: 1.50,
    trackedStoresCount: 3,
    totalSubmissionsCount: 42,
    historicalPrices: generateHistoricalPricePoints('prod-dry-cleaning', 19.00, SEED_STORES.slice(0, 3), 'hike', '1 suit'),
    isVerified: true,
    tags: ['services', 'cleaning', 'garment', 'dry-cleaning'],
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z',
  },
];

// Sample Ground-Truth OCR Documents for Multimodal Pipeline & Testing
export const SAMPLE_OCR_RESULTS: Record<string, OcrParseResult> = {
  shelfTag: {
    id: 'ocr-sample-shelf-1',
    sourceImageUrl: '/samples/shelf-tag-milk.jpg',
    detectedStoreName: 'Target',
    detectedDate: '2026-08-20',
    sourceType: 'photo_shelf',
    processingTimeMs: 340,
    confidenceAverage: 0.96,
    modelUsed: 'google/gemini-2.5-flash',
    rawText: 'HORIZON ORGANIC WHOLE MILK 1 GAL $4.89 (WAS $5.49)',
    extractedItems: [
      {
        tempId: 'item-1',
        name: 'Horizon Organic Whole Milk',
        brand: 'Horizon Organic',
        category: 'groceries',
        price: 4.89,
        originalPrice: 5.49,
        unit: '1 Gallon',
        confidence: 0.96,
        boundingBox: {
          xMin: 12.5,
          yMin: 22.0,
          xMax: 84.0,
          yMax: 68.0,
          confidence: 0.96,
          label: 'Whole Milk Price Tag',
        },
        storeName: 'Target',
        matchedProductId: 'prod-milk',
        selected: true,
      },
    ],
  },
  promoFlyer: {
    id: 'ocr-sample-flyer-1',
    sourceImageUrl: '/samples/weekly-flyer-circular.jpg',
    detectedStoreName: 'Walmart Supercenter',
    detectedDate: '2026-08-22',
    sourceType: 'promo_pamphlet',
    processingTimeMs: 820,
    confidenceAverage: 0.88,
    modelUsed: 'google/gemini-2.5-flash',
    rawText: 'WEEKLY SAVINGS: Vital Farms Eggs $5.49 | Boudin Sourdough $3.99 | Bounty 6pk $11.99 | Kerrygold $4.29',
    extractedItems: [
      {
        tempId: 'deal-1',
        name: 'Vital Farms Pasture-Raised Eggs',
        brand: 'Vital Farms',
        category: 'groceries',
        price: 5.49,
        originalPrice: 6.49,
        unit: '12 ct',
        confidence: 0.92,
        boundingBox: {
          xMin: 5.0,
          yMin: 8.0,
          xMax: 48.0,
          yMax: 45.0,
          confidence: 0.92,
          label: 'Eggs Promotion',
        },
        storeName: 'Walmart Supercenter',
        matchedProductId: 'prod-eggs',
        selected: true,
      },
      {
        tempId: 'deal-2',
        name: 'Boudin Sourdough Bread',
        brand: 'Boudin Bakery',
        category: 'groceries',
        price: 3.99,
        originalPrice: 4.69,
        unit: '24 oz',
        confidence: 0.89,
        boundingBox: {
          xMin: 52.0,
          yMin: 8.0,
          xMax: 95.0,
          yMax: 45.0,
          confidence: 0.89,
          label: 'Sourdough Promotion',
        },
        storeName: 'Walmart Supercenter',
        matchedProductId: 'prod-bread',
        selected: true,
      },
      {
        tempId: 'deal-3',
        name: 'Bounty Paper Towels 6 Double Rolls',
        brand: 'Bounty',
        category: 'household',
        price: 11.99,
        originalPrice: 14.99,
        unit: '6 rolls',
        confidence: 0.86,
        boundingBox: {
          xMin: 5.0,
          yMin: 52.0,
          xMax: 48.0,
          yMax: 92.0,
          confidence: 0.86,
          label: 'Paper Towels Promotion',
        },
        storeName: 'Walmart Supercenter',
        matchedProductId: 'prod-paper-towels',
        selected: true,
      },
      {
        tempId: 'deal-4',
        name: 'Kerrygold Pure Irish Butter',
        brand: 'Kerrygold',
        category: 'groceries',
        price: 4.29,
        originalPrice: 5.19,
        unit: '8 oz',
        confidence: 0.85,
        boundingBox: {
          xMin: 52.0,
          yMin: 52.0,
          xMax: 95.0,
          yMax: 92.0,
          confidence: 0.85,
          label: 'Butter Promotion',
        },
        storeName: 'Walmart Supercenter',
        matchedProductId: 'prod-butter',
        selected: true,
      },
    ],
  },
  receipt: {
    id: 'ocr-sample-receipt-1',
    sourceImageUrl: '/samples/grocery-receipt-trader-joes.jpg',
    detectedStoreName: "Trader Joe's",
    detectedDate: '2026-08-23',
    sourceType: 'receipt',
    processingTimeMs: 610,
    confidenceAverage: 0.91,
    modelUsed: 'google/gemini-2.5-flash',
    rawText: "TRADER JOE'S #124 - Honeycrisp Apples $4.49, Dark Roast Peet's $9.99, Method Soap $3.99, TOTAL $18.47",
    extractedItems: [
      {
        tempId: 'rec-1',
        name: 'Honeycrisp Apples',
        brand: 'Stemilt Growers',
        category: 'groceries',
        price: 4.49,
        confidence: 0.95,
        boundingBox: {
          xMin: 10.0,
          yMin: 25.0,
          xMax: 90.0,
          yMax: 32.0,
          confidence: 0.95,
          label: 'Item 1: Apples',
        },
        storeName: "Trader Joe's",
        matchedProductId: 'prod-apples',
        selected: true,
      },
      {
        tempId: 'rec-2',
        name: "Peet's Coffee Beans 12oz",
        brand: "Peet's Coffee",
        category: 'beverages',
        price: 9.99,
        confidence: 0.91,
        boundingBox: {
          xMin: 10.0,
          yMin: 34.0,
          xMax: 90.0,
          yMax: 41.0,
          confidence: 0.91,
          label: 'Item 2: Coffee',
        },
        storeName: "Trader Joe's",
        matchedProductId: 'prod-coffee',
        selected: true,
      },
      {
        tempId: 'rec-3',
        name: 'Method Dish Soap 28oz',
        brand: 'Method',
        category: 'household',
        price: 3.99,
        confidence: 0.88,
        boundingBox: {
          xMin: 10.0,
          yMin: 43.0,
          xMax: 90.0,
          yMax: 50.0,
          confidence: 0.88,
          label: 'Item 3: Dish Soap',
        },
        storeName: "Trader Joe's",
        matchedProductId: 'prod-dish-soap',
        selected: true,
      },
    ],
  },
};
